eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
      
server:
  port: 8764
  
spring:
  application:
    name: inventory-server
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411